openapi: 3.0.0
info:
  title: backend
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3000'
paths:
  /user-items:
    get:
      summary: 用户列表
      tags: []
      responses: {}
      operationId: get-user-items
      description: user Items
  /user-delete:
    get:
      summary: 删除用户
      tags: []
      responses: {}
      operationId: get-user-delete
      requestBody: {}
components:
  schemas:
    User:
      title: ''
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        password:
          type: string
      description: 用户
